### PR TITLE
PPU Improvement

### PR DESCRIPTION
**Pull request by GorgonMeducer**
- Seperate PPU into two versions, one for scanline based and one for partial-scanline based (while another part is pixel based)
- Apply compact dual pixels to background buffer
   TODO: Fix debug mode
- Improve readability
- Improve the sprite Y order sorting algorithm
    Only updates the Y order list when Y axis of any sprites are changed
- Introduce background buffer (~10% performance improvement)
- Add full support for 4 name table mirroring.

### CODE REVIEW

**Comment by GorgonMeducer** [comment]
I have introduced background buffer to the ppu. It might be a big change, so I separate the ppu.c into different versions.

**Comment by semiversus** [comment]
Good work! Will have a deeper look into it at night.

**Comment by semiversus** [comment]
The new change introduced a problem in my test roms. A test with sprites is reporting a problem. Will have a look into it. You are using ppu_pixel_based.c for your project, is it? Will build back ppu.c and work on my optimization ideas.

**Comment by GorgonMeducer** [comment]
I am curious what the issue and what the reason behind. I will continuously contribute to both ppu version. But I can stop a while for ppu.c and wait for your update.

**Pull request merged**
