### PR TITLE
PPU sprites processing update

### PR DESCRIPTION
**Pull request by GorgonMeducer**
- Increasing the maximum allowed sprites on a single scanline
- extract a dedicated function for fetching sprite info on a specified line, fetch_sprite_info_on_specified_line()
- Add a Y-order-list to avoid unnecessary sprite info scanning
- Add dirty bit for oam_data to avoid unnecessary Y-order-list update.
- simplify the OAM access with structure and bit-fields

### CODE REVIEW

**Comment by GorgonMeducer** [comment]
Just for your information, I will push another PPU dedicated request in three days.
Cheers,
Gabriel

**Comment by semiversus** [comment]
### Maximum allowed sprites per line

merged it, but set default to 8 as the test roms would fail

### Sprite optimisations

I like the idea. I'm not sure if it would change the behavior of emulation. The current test roms are ok with this, but I don't have a special sprite testing rom in my test cases.

Another point: My benchmark shows 4% decrease with this change. Do you see an improvement?

### simplify the OAM access with structure and bit-fields

OK. Maybe jeg_cfg.h is not the right place to define ``_BV``.

**Comment by GorgonMeducer** [comment]
I believe this optimisation should improve the performance, and in fact, I have observed a 9% improvement on my side (440ms -> 401ms). If you check the scheme, it is obviously saving cycles. But I guess the x86 has some fansy optimisation which is affected by this low level changing, that’s why you see the 4% decreasing. 

I usually put _BV in compiler.h, but I don’t want to make jeg depending on some external header file, so I put it in jeg_cfg.h (which is supposed to be included by all files of JEG)

**Comment by GorgonMeducer** [comment]
This optimisation is an equivilant refactory, so the logic is actually the same. I believe it will not change the behaviour of emulation.

**Comment by semiversus** [comment]
Added (temporary) flag to jeg_cfg.h: ``JEG_USE_OPTIMIZED_SPRITE_PROCESSING``. Default is Enabled. Will remove the flag as soon as I've reviewed the changes and have the original performance back.

**Comment by semiversus** [comment]
Removed includes of ``jeg_cfg.h`` in files where it is not used. Understand it now as _BV should be available everywhere. I'm thinking of using something like automake to create the jeg_cfg.h via ./configure script

**Comment by GorgonMeducer** [comment]
Thank you. And do you still see the 4% performance decreasing?

**Comment by semiversus** [comment]
Yes, still 4% depending on OPTIMZED_SPRITE_PROCESSING. Will look into this issue with a profiler.

**Pull request merged**
