### PR TITLE
Memory access improvement

### PR DESCRIPTION
**Pull request by GorgonMeducer**
- Re-factory memory access to improve performance
- improve readability
- use uint_fastx_t to replace the original native data type. Balancing between portability and performance. 
NOTE: The re-factory doesn't change the original logic. The code has been verified.

### CODE REVIEW

**Comment by semiversus** [comment]
Closing this pull request - merged most of it, but some things are special:
* Removed 16bit interface
* Removed special DMA handling (it's really seldom used in games)
* Didn't merged the interface for drawing pixels (but will come in future)
* Had to make adaptations to pass all the test roms

Overall it improved the benchmark (running 1000 frames) by 2.7%. More to come...

**Comment by GorgonMeducer** [comment]
Thanks!
Just one thing, could I add macros to make the 16bit read interface and dedicated dma interface an optimisation option? I do see the improvements on my poor cortex-m platform. due to the very limited computing power, I have to do the cycle level optimisation.

**Comment by GorgonMeducer** [comment]
I am doing next around update and will send a pull request again:

- Adding macros to enable/disable optimisation options
- using the latest ppu_upate

Cheers,
Gabriel

**Comment by semiversus** [comment]
Could you keep the pull request rather small - going optimisation by optimisation? It's easier for me to understand and merge it and we can discuss the pull requests separately.

**Pull request closed without merging**
